packages/storybook/package.json
yarn.lock

Related to the latest fix in `storybook deployer`: https://github.com/storybookjs/storybook-deployer/pull/102

build(cli deploy): bump storybook-deployer to 2.8.8

---

packages/cxl-ui/src/components/cxl-paywall.js
packages/storybook/cxl-ui/cxl-paywall.stories.js

Adds the ability to specify the dialog content from the outside. Constraints are that `<div slot="message"></div>` needs to have only one direct child to act as the wrapper.
```
<cxl-paywall>
<div slot="message">
<div id="sample-wrapper">###DIALOG CONTENT###</div>
</div>
###CONTENT###
</cxl-paywall>
```
It should support text/html.

cxl paywall message

---

packages/cxl-lumo-styles/scss/global.scss

Issue: #196 
Inspired by:
- [WordPress/wporg-news-2021@`20f1bde` (#178)](https://github.com/WordPress/wporg-news-2021/pull/178/commits/20f1bde806e27cace085d8a53709e6d7e203eb6f)
- [WordPress/wporg-news-2021@`3106b25` (#178)](https://github.com/WordPress/wporg-news-2021/pull/178/commits/3106b259751b48321145f9bbf82e342b8ea2d7a8)
- https://github.com/WordPress/WordPress/commit/e32d9ec5226ec01e4a2de3cec4a4da0582d1d52c

fix(cxl-lumo-styles): add CSS `top` property to `headroom`

---

packages/cxl-lumo-styles/scss/themes/vaadin-context-menu-item.scss
packages/cxl-ui/scss/global/cxl-marketing-nav.scss
packages/cxl-ui/src/components/cxl-marketing-nav.js
packages/storybook/cxl-ui/cxl-marketing-nav.data.json

Closed old PRs:
- https://github.com/conversionxl/aybolit/pull/89
- https://github.com/conversionxl/aybolit/pull/76
and created fresh branch & PR by bringing the changes from above PRs.

feat(cxl-ui): [cxl-marketing-nav] add descriptions

---

packages/cxl-lumo-styles/package.json
packages/cxl-ui/package.json
packages/storybook/package.json

Versions: 1.1.0, 1.1.1 and 1.1.2 which are published in registry are missing from the repository due the lack of possibility to push directly to `master` branch and @pawelkmpt mistake.
Trying to work it around by PRs would take too much time.
* https://npm.cxl.co/-/web/detail/@conversionxl/cxl-ui/v/1.1.1
* https://npm.cxl.co/-/web/detail/@conversionxl/cxl-ui/v/1.1.2
* https://npm.cxl.co/-/web/detail/@conversionxl/cxl-lumo-styles/v/1.1.2

chore(cxl-lumo-styles,cxl-ui): v1.2.0

---

packages/cxl-ui/src/components/cxl-marketing-nav.js

* https://app.clickup.com/t/3pqkb2a
* Only set `hidden` property if description element itself exists

fix(cxl-ui): `<cxl-marketing-nav>` descriptions

---

packages/cxl-lumo-styles/scss/global.scss

When a list is placed on the sales page, WP block styles leak in. We need more styles to keep expected look

fix(cxl-lumo-styles): 862c0f1

---

packages/cxl-lumo-styles/scss/global.scss
packages/cxl-ui/scss/cxl-stats.scss
packages/cxl-ui/scss/global/cxl-stats.scss
packages/cxl-ui/src/components/cxl-stats.js
packages/cxl-ui/src/index-core.js
packages/cxl-ui/src/index-storybook.js
packages/storybook/cxl-ui/cxl-stats/cxl-stats.data.json
packages/storybook/cxl-ui/cxl-stats/default.stories.js

https://app.clickup.com/t/861n0qjxj

feat(cxl-ui): add cxl-stats component

---

packages/cxl-lumo-styles/scss/_mixins.scss
packages/cxl-lumo-styles/scss/global.scss
packages/cxl-lumo-styles/scss/themes/vaadin-accordion.scss
packages/cxl-lumo-styles/scss/themes/vaadin-notification-card.scss
packages/cxl-ui/scss/cxl-app-layout.scss
packages/cxl-ui/scss/cxl-app-layout/_layout-1c-w.scss
packages/cxl-ui/scss/cxl-section.scss
packages/cxl-ui/scss/global/cxl-app-layout.scss
packages/cxl-ui/scss/global/cxl-vaadin-accordion.scss
packages/storybook/cxl-ui/cxl-app-layout/layout=1c-c.stories.js
packages/storybook/cxl-ui/cxl-app-layout/layout=1c-w.stories.js
packages/storybook/cxl-ui/cxl-app-layout/layout=2c-l.stories.js
packages/storybook/cxl-ui/cxl-app-layout/layout=2c-r.stories.js
packages/storybook/cxl-ui/cxl-tabs-slider/cxl-tabs-slider.stories.js
packages/storybook/cxl-ui/footer-nav.stories.js

Re-orient from `--cxl-wrap-width` to `--cxl-content-max-width`, communicates intent clearer.
Will probably require some refactor in app CSS.
**1080p BEFORE**
**1080p AFTER**

refactor(cxl-lumo-styles): unwrap lets app use large screen estate

---

packages/cxl-ui/scss/cxl-base-card.scss
packages/cxl-ui/scss/cxl-course-card.scss
packages/cxl-ui/scss/cxl-time.scss
packages/cxl-ui/src/components/cxl-base-card.js
packages/cxl-ui/src/components/cxl-course-card.js
packages/cxl-ui/src/components/cxl-time.js
packages/storybook/cxl-ui/cxl-time.stories.js

Tasks: 
- https://app.clickup.com/t/862k6unkf
- https://app.clickup.com/t/862k77fbg
The new cxlBaseCard class should be used for all CXL 2.0 course cards. It does not register as a customElement, so it needs to be extended by new target classes. As implemented here, `cxl-course-card` is complete, while `cxl-feature-course-card` and `cxl-light-card` should only need some additional CSS.

refactor(cxl-ui): add cxlBaseCardElement as base class

---

packages/cxl-lumo-styles/scss/badge.scss
packages/cxl-lumo-styles/scss/global.scss
packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
packages/cxl-ui/scss/cxl-light-card.scss
packages/cxl-ui/scss/cxl-time.scss
packages/cxl-ui/src/components/cxl-base-card.js
packages/cxl-ui/src/components/cxl-card.js
packages/cxl-ui/src/components/cxl-light-card.js
packages/storybook/cxl-ui/cxl-course-card/[theme=playbook].stories.js
packages/storybook/cxl-ui/cxl-course-card/[theme=training].stories.js
packages/storybook/cxl-ui/cxl-course-card/[theme=video].stories.js
packages/storybook/cxl-ui/cxl-course-card/template.js
packages/storybook/cxl-ui/cxl-light-card/default.stories.js
packages/storybook/cxl-ui/cxl-light-card/light-card-slider.stories.js

https://app.clickup.com/t/861n0qm47

feat: add dashboard lightweight card

---

packages/cxl-lumo-styles/scss/themes/vaadin-tab.scss
packages/cxl-lumo-styles/scss/themes/vaadin-tabs.scss
packages/cxl-ui/scss/cxl-featured-course-card.scss
packages/cxl-ui/src/components/cxl-base-card.js
packages/cxl-ui/src/components/cxl-featured-course-card.js
packages/storybook/cxl-ui/cxl-featured-course-card/dashboard-slider.stories.js
packages/storybook/cxl-ui/cxl-featured-course-card/default.stories.js
yarn.lock

https://app.clickup.com/t/861n0qjha

feat: add featured course card component

---

packages/cxl-lumo-styles/scss/global.scss
packages/cxl-lumo-styles/scss/themes/vaadin-context-menu-item.scss
packages/cxl-lumo-styles/scss/themes/vaadin-context-menu-list-box.scss
packages/cxl-lumo-styles/scss/themes/vaadin-overlay.scss
packages/cxl-lumo-styles/scss/themes/vaadin-tab.scss
packages/cxl-ui/scss/cxl-marketing-nav.scss
packages/cxl-ui/scss/global/cxl-marketing-nav.scss
packages/cxl-ui/src/components/cxl-marketing-nav.js
packages/storybook/cxl-ui/cxl-marketing-nav.data.json
packages/storybook/cxl-ui/cxl-marketing-nav.stories.js
scripts/watcher.js

Could not find a way to change the box shadow on vaadin-context-menu-list-box elements
https://app.clickup.com/t/861mx0nwm
https://www.figma.com/file/RTj2PtUSrCOUFtljOiq0W3/Dashboard?type=design&node-id=291-78069&mode=design

feat: update navigation

---

packages/cxl-ui/src/components/cxl-base-card.js

[PR](https://github.com/conversionxl/cxl-wpstarter/pull/199) needed `cxl-base-card` changes. So the layout will not be broken if any of the data haven't been added to the cards.

fix(cxl-ui): add checks for missing data

---

packages/cxl-lumo-styles/scss/themes/vaadin-tab.scss
packages/cxl-ui/scss/cxl-featured-course-card.scss
packages/storybook/cxl-ui/cxl-featured-course-card/dashboard-slider.stories.js

Fix some style issues that came up during this development: https://github.com/conversionxl/cxl-wpstarter/pull/197

fix(cxl-ui): fix `cxl-featured-course-card` slider width and paddings

---

packages/cxl-ui/scss/_mixins.scss
packages/cxl-ui/scss/cxl-base-card.scss
packages/cxl-ui/scss/cxl-course-card.scss
packages/cxl-ui/src/components/cxl-base-card.js
packages/cxl-ui/src/components/cxl-course-card.js
packages/storybook/cxl-ui/cxl-course-card/[theme=playbook].stories.js
packages/storybook/cxl-ui/cxl-course-card/[theme=training].stories.js
packages/storybook/cxl-ui/cxl-course-card/[theme=video].stories.js
packages/storybook/cxl-ui/cxl-course-card/course-dashboard-varying-heights.stories.js
packages/storybook/cxl-ui/cxl-course-card/template.js

Solves issues discussed [here](https://cxlworld.slack.com/archives/C04TL31HNG5/p1693406189748419).
Card height is now fixed to 345px. Check "Course Dashboard different heights" for examples

fix(cxl-ui): make changes to allow for fixed height course cards

---

packages/cxl-ui/src/components/cxl-dashboard-header.js
packages/cxl-ui/src/components/cxl-dashboard-notification.js
packages/storybook/cxl-ui/cxl-dashboard-header/template.stories.js

This was not part of the sprint, but an issue identified while working on a different task. 
The component `cxl-dashboard-header` was importing `cxl-dashboard-notification` **storybook** code and example data to use inside the elements template, seemingly instead of importing and using the actual element. I'm not sure what was the idea behind it, but it's 100% incorrect usage of both custom elements and stories, so I decided to preemptively correct it. 
The updated code was tested in storybook and local wp starter environment.

fix(cxl-ui): remove bad usage of storybook stories in component class

---

packages/cxl-lumo-styles/scss/themes/vaadin-context-menu-item.scss
packages/cxl-lumo-styles/scss/themes/vaadin-context-menu-list-box.scss
packages/cxl-lumo-styles/scss/themes/vaadin-overlay.scss
packages/cxl-lumo-styles/scss/themes/vaadin-tabs.scss
packages/cxl-ui/scss/global/cxl-marketing-nav.scss
packages/cxl-ui/src/components/cxl-marketing-nav.js

https://app.clickup.com/t/86aybcq9a
The main bug is fixed, but this also includes fixes other user experience issues:
- nav bar is now scrolling enabled, scroll buttons had the wrong color and were not visible 
- Odd states emerged from too many different responsiveness thresholds
- small layout and design fixes

feat(cxl-ui): improve navigation responsiveness

---

packages/cxl-ui/scss/cxl-base-card.scss
packages/cxl-ui/scss/cxl-course-card.scss
packages/storybook/.storybook/preview-body.html
packages/storybook/cxl-ui/cxl-course-card/[theme=playbook].stories.js
packages/storybook/cxl-ui/cxl-course-card/[theme=training].stories.js
packages/storybook/cxl-ui/cxl-course-card/[theme=video].stories.js
packages/storybook/cxl-ui/cxl-course-card/course-card-slider.stories.js
packages/storybook/cxl-ui/cxl-course-card/template.js
packages/storybook/cxl-ui/cxl-featured-course-card/default.stories.js
packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-dashboard-category.story.js

https://app.clickup.com/t/86ayagj21

fix(cxl-ui): fix course card layout issues

---

.gitignore
packages/cxl-lumo-styles/scss/color.scss
packages/cxl-lumo-styles/scss/global.scss
packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
packages/cxl-lumo-styles/scss/themes/vaadin-details.scss
packages/cxl-ui/scss/cxl-dashboard-header.scss
packages/cxl-ui/scss/cxl-dashboard-notification.scss
packages/cxl-ui/scss/cxl-featured-course-card.scss
packages/cxl-ui/scss/cxl-stats.scss
packages/cxl-ui/scss/global/cxl-dashboard-header.scss
packages/cxl-ui/scss/global/cxl-stats.scss
packages/cxl-ui/src/components/cxl-featured-course-card.js
packages/storybook/cxl-ui/cxl-featured-course-card/dashboard-slider.stories.js
packages/storybook/cxl-ui/cxl-featured-course-card/default.stories.js

https://app.clickup.com/t/86aya2ta8

feat(cxl-ui): cxl-featured-course-card v2

---

packages/cxl-ui/scss/cxl-base-card.scss
packages/cxl-ui/scss/cxl-course-card.scss
packages/cxl-ui/src/components/cxl-course-card.js
packages/cxl-ui/src/components/cxl-course-dialog.js
packages/storybook/cxl-ui/cxl-course-card/[theme=video].stories.js
packages/storybook/cxl-ui/cxl-course-card/course-dashboard-varying-heights.stories.js
packages/storybook/cxl-ui/cxl-course-card/template.js
packages/storybook/cxl-ui/cxl-course-dialog/default.stories.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-layout.stories.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-no-content.stories.js

https://app.clickup.com/t/86ayfxnan

fix(cxl-ui): add missing card hover styles

---

packages/cxl-lumo-styles/scss/themes/vaadin-overlay.scss

🚀  Already live
Submenu was not opening on tall (> 768px) mobile devices.
https://cxlworld.slack.com/archives/C01JABH8AHX/p1697400946534649

fix(cxl-lumo-styles): cxl-marketing-nav submenu not opening on tall mobile a9818ad

---

packages/cxl-ui/src/components/cxl-marketing-nav.js

https://app.clickup.com/t/86ayaanv9
Fixes empty menu bugs in some pages. Due to a timing issue, the menu overlays wrapper can get a maxHeight set to 0, preventing menu lists from showing the items.

fix(cxl-ui): fix wrong nav overlays-wrapper height

---

packages/cxl-ui/src/components/cxl-app-layout.js

https://app.clickup.com/t/86ayjqt93

fix(cxl-ui): fix app-layout wide media query

---

packages/cxl-ui/scss/_mixins.scss
packages/cxl-ui/scss/cxl-dashboard-section.scss
packages/cxl-ui/scss/global/cxl-dashboard-section.scss
packages/cxl-ui/src/components/cxl-dashboard-section.js
packages/cxl-ui/src/index-core.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-layout.stories.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-section.stories.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-sections.stories.js
packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-dashboard-category.data.json

https://app.clickup.com/t/86ayj5cv3

feat(cxl-ui): add cxl-dashboard-section component

---

packages/cxl-ui/src/components/cxl-marketing-nav.js

Fixes lesson action bar `vaadin-context-menu` not closing on outside click
related: https://github.com/conversionxl/cxl-wpstarter/pull/264

fix(cxl-ui): context-menu does not close on outside click

---

packages/cxl-ui/src/components/cxl-dashboard-team-header.js
packages/cxl-ui/src/components/cxl-dashboard-team-stats.js
packages/storybook/cxl-ui/cxl-team-dashboard/cxl-dashboard-team-header.stories.js
packages/storybook/cxl-ui/cxl-team-dashboard/cxl-dashboard-team-stats.stories.js
packages/storybook/cxl-ui/cxl-team-dashboard/cxl-team-dashboard.stories.js
packages/storybook/cxl-ui/cxl-team-dashboard/header-template.js
packages/storybook/cxl-ui/cxl-team-dashboard/stats-template.js

https://app.clickup.com/t/86ayqff97

fix(Team Dashboard): conditional visibility of buttons

---

packages/cxl-ui/src/components/cxl-dashboard-team-stats.js
packages/storybook/cxl-ui/cxl-team-dashboard/cxl-dashboard-team-stats.stories.js
packages/storybook/cxl-ui/cxl-team-dashboard/cxl-team-dashboard.stories.js
packages/storybook/cxl-ui/cxl-team-dashboard/stats-template.js

https://app.clickup.com/t/86ayqffyf

feat(Team Dashboard): Temporarily hide team stats block

---

.gitignore
packages/cxl-lumo-styles/scss/global.scss
packages/cxl-lumo-styles/scss/themes/vaadin-button.scss
packages/cxl-lumo-styles/scss/typography.scss
packages/cxl-lumo-styles/src/themes.js
packages/cxl-ui/scss/cxl-base-card.scss
packages/cxl-ui/scss/cxl-course-card.scss
packages/cxl-ui/scss/cxl-dashboard-notification.scss
packages/cxl-ui/scss/cxl-light-card.scss
packages/cxl-ui/scss/cxl-like-or-dislike.scss
packages/cxl-ui/scss/cxl-section.scss
packages/cxl-ui/scss/global/cxl-app-layout.scss
packages/cxl-ui/scss/global/cxl-card.scss
packages/cxl-ui/scss/global/cxl-course-dialog.scss
packages/cxl-ui/scss/global/cxl-playbook-accordion.scss
packages/cxl-ui/scss/global/cxl-vaadin-accordion.scss
packages/cxl-ui/scss/jw-player/chapter.scss
packages/cxl-ui/src/components/cxl-section.js
packages/storybook/cxl-lumo-styles/typography.stories.js

https://app.clickup.com/t/861mhf04m

refactor(cxl-lumo-styles): update cxl-lumo-styles and storybook

---

packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss

https://app.clickup.com/t/86ayt61gb
Slider buttons are positioned overlapping cards on each end of the the slider, which makes users inadvertently click the card below the button when they reach the end of the list. 
Adding padding would make the cards indented too far in, hurting the dashboard design. Moving the buttons slightly outward fixes the UX issue without disrupting the visual aspect significantly.

fix(cxl-ui): cxl-tabs-slider - improve usability of scroller buttons

---

packages/cxl-lumo-styles/scss/global.scss

As requested in [cxl-wpstarter PR](https://github.com/conversionxl/cxl-wpstarter/pull/283#pullrequestreview-1757302024)
Tested locally:

fix(cxl-lumo-styles): limit secondary font style in ul to .entry-content

---

packages/cxl-ui/scss/cxl-section.scss
packages/cxl-ui/scss/global/cxl-section.scss

From discussion: https://cxlworld.slack.com/archives/C01HXUNGEPM/p1701945675624519

refactor(cxl-ui): cxl-section - remove top margin

---

packages/cxl-lumo-styles/scss/_mixins.scss
packages/cxl-lumo-styles/scss/color.scss
packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
packages/cxl-lumo-styles/scss/themes/vaadin-tab.scss
packages/cxl-lumo-styles/scss/typography.scss
packages/cxl-ui/scss/cxl-dashboard-header.scss
packages/cxl-ui/scss/cxl-dashboard-notification.scss
packages/cxl-ui/scss/cxl-featured-course-card.scss
packages/cxl-ui/scss/cxl-section.scss
packages/cxl-ui/scss/global/cxl-app-layout.scss
packages/cxl-ui/scss/global/cxl-dashboard-header.scss
packages/cxl-ui/scss/global/cxl-dashboard-section.scss
packages/cxl-ui/src/components/cxl-dashboard-header.js
packages/storybook/cxl-ui/cxl-dashboard-header/dashboard-header.stories.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-layout.stories.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-sections.stories.js
packages/storybook/cxl-ui/cxl-stats/default.stories.js

https://app.clickup.com/t/86ayt69ga
dependencies: #365

refactor(cxl-ui): implement dashboard facelift

---

packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
packages/cxl-ui/scss/cxl-dashboard-header.scss
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-layout.stories.js
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-sections.stories.js

Fix bug layout issue identified in QA:
https://cxlworld.slack.com/archives/C01HXUNGEPM/p1702916460651049?thread_ts=1702898312.077949&cid=C01HXUNGEPM

fix(cxl-ui): cxl-dashboard-header -> remove unnecessary padding

---

packages/cxl-lumo-styles/scss/themes/vaadin-button.scss
packages/cxl-ui/scss/cxl-marketing-nav.scss
packages/cxl-ui/src/components/cxl-marketing-nav.js

Add `logoBar` property to define on which menu bar CXL logo should be displayed. It's needed when we want to display just a single primary menu bar (white), which didn't have CXL logo displayed by default.

refactor(cxl-ui): cxl-marketing-nav logo placement; border color

---

packages/cxl-ui/scss/cxl-dashboard-header.scss
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-sections.stories.js

https://cxlworld.slack.com/archives/C01HXUNGEPM/p1703076394376169

fix(cxl-lumo-styles): cxl-dashboard-header -> mobile layout inline padding

---

packages/cxl-ui/src/components/cxl-marketing-nav.js

Open Intercom chat widget when user clicks on the menu item with `.menu-item-help` class.

feat(cxl-ui): cxl-marketing-nav open Intercom for .menu-item-help

---

packages/cxl-lumo-styles/scss/global.scss
packages/cxl-lumo-styles/scss/typography.scss
packages/cxl-ui/scss/cxl-base-card.scss
packages/cxl-ui/scss/cxl-course-card.scss
packages/cxl-ui/scss/cxl-credential.scss
packages/cxl-ui/scss/cxl-dashboard-header.scss
packages/cxl-ui/scss/cxl-featured-course-card.scss
packages/cxl-ui/scss/cxl-light-card.scss
packages/cxl-ui/scss/global/cxl-dashboard-section.scss
packages/cxl-ui/src/components/cxl-base-card.js
packages/cxl-ui/src/components/cxl-course-card.js
packages/cxl-ui/src/components/cxl-course-dialog.js
packages/cxl-ui/src/components/cxl-light-card.js
packages/storybook/.storybook/preview-head.html
packages/storybook/cxl-ui/cxl-dashboard/cxl-dashboard-sections.stories.js

Clickup: https://app.clickup.com/t/86ayy0gy1

feat(cxl-lumo-styles): update typography

---

packages/cxl-ui/scss/cxl-base-card.scss
packages/cxl-ui/scss/cxl-dashboard-header.scss
packages/cxl-ui/scss/cxl-dashboard-section.scss
packages/cxl-ui/src/components/cxl-course-card.js
packages/cxl-ui/src/components/cxl-dashboard-header.js

* remove new (star) icon
* make tag more prominent, styled as one from cxl-light-card
https://app.clickup.com/t/86az50h3y?comment=90140017966111
BEFORE
AFTER

refactor(cxl-ui): cxl-course-card, dashboard

---

packages/cxl-ui/scss/global/cxl-certificate-header.scss
packages/cxl-ui/src/components/cxl-certificate-header.js

https://app.clickup.com/t/86azbhf5m
Desktop:
Mobile:

feat(cxl-ui): [cxl-certificate-header] update completed page

---

packages/cxl-ui/scss/cxl-featured-course-card.scss

https://app.clickup.com/t/86b00z797

feat(cxl-ui): center instructor image

---

packages/cxl-ui/src/components/cxl-star-rating.js

This is necessary to prevent the component from saving default value on each usage case.
We prefer it being zero at all times.
https://app.clickup.com/t/86azy6kx9?comment=90140034479841&threadedComment=90140035014093

refactor(cxl-ui): cxl-star-rating remove _updateReadonlyAndValue

---

packages/cxl-ui/scss/cxl-course-card.scss
packages/cxl-ui/scss/global/cxl-course-card.scss
packages/cxl-ui/src/components/cxl-course-card.js

https://cxlworld.slack.com/archives/C01HNLQNVA9/p1715760558848559

feat(cxl-ui): cxl-course-card update styles when on large devices

---

packages/cxl-ui/scss/global/cxl-app-layout.scss

https://cxlworld.slack.com/archives/C06N0STGZQW/p1721062995105759

fix(cxl-ui): cxl-app-layout add padding only on desktop

---

packages/cxl-ui/scss/global/cxl-app-layout.scss

https://app.clickup.com/t/86b1b91mm

fix(cxl-ui): cxl-app-layout remove iframe styles

---

packages/cxl-ui/scss/cxl-inline-notification.scss
packages/cxl-ui/src/components/cxl-inline-notification.js
packages/cxl-ui/src/index-institute.js
packages/storybook/cxl-ui/cxl-inline-notification.stories.js

https://app.clickup.com/t/86b02c865

feat(cxl-ui): cxl-inline-notification add component

---

packages/cxl-lumo-styles/scss/global.scss

https://app.clickup.com/t/86b1dy579

feat(cxl-lumo-styles): increase blog font size

---

packages/cxl-ui/src/components/cxl-jw-player/mixins/BaseMixin.js
packages/cxl-ui/src/components/cxl-jw-player/mixins/TranscriptMixin.js

https://cxlworld.slack.com/archives/C01HXU5GGJG/p1728286680812039

fix(cxl-ui): cxl-jw-player handle tracks which are improperly formatted

---

packages/cxl-ui/scss/cxl-marketing-nav.scss

https://app.clickup.com/t/86b2hv84w

fix(cxl-ui): cxl-marketing-nav menu bar button alignment

---

packages/cxl-ui/scss/cxl-marketing-nav.scss
packages/cxl-ui/scss/global/cxl-marketing-nav.scss
packages/cxl-ui/src/components/cxl-marketing-nav.js

https://app.clickup.com/t/86b2hv84w
Desktop:
Mobile:

fix(cxl-ui): cxl-marketing-nav menu bar button alignment on desktop
