conversionxl/aybolit

- packages/cxl-lumo-styles/scss/themes/vaadin-accordion-panel.scss
- packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-faq.data.json
- packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-faq.stories.js
> feat(cxl-ui): cxl-vaadin-accordion theme="cxl-faq", fix #37

- packages/cxl-ui/scss/global/cxl-vaadin-accordion.scss
Reference: https://github.com/conversionxl/aybolit/issues/116
> refactor(cxl-ui): lighter accordion thumbnail

- packages/cxl-lumo-styles/src/icons.js
- packages/storybook/cxl-ui/cxl-app-layout/layout=2c-l.stories.js
- packages/storybook/cxl-ui/cxl-vaadin-accordion.stories.js
- packages/storybook/cxl-ui/cxl-vaadin-accordion/cxl-playbook-accordion.story.js
Deploy: https://comment-hover-icon.netlify.app/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cl
Video: https://www.loom.com/share/4f0d0af8d4bd481995c3a88a8481d938
> Playbook Viewer: comment hover icon

- packages/cxl-ui/src/components/cxl-playbook-accordion.js
- packages/cxl-ui/src/components/cxl-playbook-progress-bar.js
- packages/cxl-ui/src/index.js
- packages/storybook/cxl-ui/cxl-app-layout/layout=2c-l.stories.js
- packages/storybook/cxl-ui/cxl-vaadin-accordion.stories.js
- packages/storybook/cxl-ui/cxl-vaadin-accordion/cxl-playbook-accordion.story.js
related issue: https://github.com/conversionxl/aybolit/issues/131
> feat(cxl-ui): add cxl-playbook-progress-bar

- packages/cxl-ui/src/components/cxl-like-or-dislike.js
Hi, 
Task: https://app.clickup.com/t/wm08h4
Expected result:
https://www.loom.com/share/c7c98ab0be32416d92587a67b4a17253
> fix: make Vote(s) string responsive to number of votes

- packages/cxl-ui/src/components/cxl-app-layout.js
Closes conversionxl/aybolit#181
> refactor(cxl-ui): add passive flag to wheel event

- packages/cxl-ui/scss/global/cxl-app-layout.scss
- packages/storybook/cxl-ui/cxl-app-layout/layout=2c-r.stories.js
https://app.clickup.com/t/1pby0c3
> feat(cxl-ui): cxl-app-layout slot name=action-bar

- packages/storybook/cxl-lumo-styles/icons-preview.js
- packages/storybook/cxl-lumo-styles/icons.stories.js
- packages/storybook/package.json
> feat(storybook): add icons story to storybook

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-notification-card.scss
- packages/cxl-ui/package.json
- packages/cxl-ui/src/components/cxl-notification.js
- packages/cxl-ui/src/index-core.js
- packages/storybook/cxl-ui/cxl-notification/defaut.story.js
- packages/storybook/cxl-ui/cxl-notification/gravity-form.story.js
- packages/storybook/cxl-ui/cxl-notification/index.stories.js
- packages/storybook/cxl-ui/cxl-notification/unpaid-order.story.js
- packages/storybook/cxl-ui/vaadin-horizontal-layout.stories.js
- packages/storybook/package.json
- yarn.lock
https://app.clickup.com/t/3d9ttgy
> [cxl-notification]

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-ui/scss/cxl-marketing-nav.scss
- packages/cxl-ui/src/components/cxl-marketing-nav.js
- packages/storybook/cxl-ui/cxl-marketing-nav.stories.js
Dep: https://github.com/conversionxl/wp-theme-lib/pull/66
cu-task parent task: https://app.clickup.com/t/2z64umf
> feat(cxl-ui): primary menu tweaks, make sticky, disable page scrolling, few fixes etc.

- packages/cxl-lumo-styles/scss/gravity-forms.scss
- packages/storybook/gravity-forms/index.stories.js
This adds a gravity form story with an optional pending state.
> feat: bring gravity forms styes and add gravity form story

- packages/cxl-lumo-styles/scss/gravity-forms.scss
> Gravity Form ajax spinner

- packages/cxl-ui/src/components/cxl-marketing-nav.js
- packages/storybook/cxl-ui/cxl-marketing-nav.data.json
https://app.clickup.com/t/861m7gmrz
> fix(cxl-ui): [cxl-marketing-nav] display descriptions on sub-menus

- packages/cxl-lumo-styles/scss/badge.scss
- packages/cxl-lumo-styles/src/badge.js
- packages/cxl-lumo-styles/src/index.js
- packages/storybook/cxl-lumo-styles/elements.stories.js
https://vaadin.com/docs/latest/components/badge
> feat(cxl-lumo-styles): add badge

- packages/cxl-ui/scss/global/cxl-vaadin-accordion.scss
https://app.clickup.com/t/860pg7x6g
> feat(cxl-ui): [cxl-vaadin-accordion] add aspect ratio to step number

- packages/cxl-ui/scss/cxl-app-layout/_layout.scss
- packages/storybook/cxl-ui/cxl-app-layout/layout=2c-r-short-content.stories.js
https://app.clickup.com/t/ptfgc9
> fix(cxl-ui): always stick action bar to the bottom 

- packages/cxl-lumo-styles/scss/global.scss
- packages/storybook/cxl-lumo-styles/ordered-list-heavy.stories.js
Clickup: https://app.clickup.com/t/861mnfcj4
Screenshot:
> feat(cxl-lumo-styles): add ordered-list-heavy class and story

- packages/cxl-lumo-styles/scss/global.scss
- packages/storybook/cxl-lumo-styles/courses-list.stories.js
Let me know if anything can be done better
https://app.clickup.com/t/865bfrhzh
> Explore more courses section

- package.json
- packages/cxl-ui/package.json
- packages/cxl-ui/scss/cxl-credential.scss
- packages/cxl-ui/src/components/cxl-credential.js
- packages/cxl-ui/src/index-core.js
- packages/storybook/cxl-ui/cxl-credential/default.stories.js
- yarn.lock
Task: https://app.clickup.com/t/862k00xn3
`<cxl-credential>` takes only the necessary info to show in the certificate, generates qr-code and supports both proposed design variations ([figma](https://www.figma.com/file/vXp29C0NOlMbIvEuY6wcNj/Untitled?type=design&node-id=1-2771&t=D7S5DPxZfkohXwr6-0))
> feat(cxl-ui): add credential (certificate) element

- packages/cxl-ui/scss/global/cxl-app-layout.scss
https://app.clickup.com/t/862k7kua0
simple fix for wide layout padding
> refactor(cxl-ui): increase cxl-app-layout[wide] padding

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-details.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-tab.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-tabs.scss
- packages/cxl-ui/scss/cxl-dashboard-notification.scss
- packages/cxl-ui/scss/cxl-notification-card.scss
- packages/cxl-ui/src/components/cxl-dashboard-notification.js
- packages/cxl-ui/src/components/cxl-notification-card.js
- packages/storybook/cxl-ui/cxl-dashboard-notification/cxl-dashboard-notification-none.data.json
- packages/storybook/cxl-ui/cxl-dashboard-notification/cxl-dashboard-notification.data.json
- packages/storybook/cxl-ui/cxl-dashboard-notification/default.stories.js
https://app.clickup.com/t/861n0qm2v
> feat(cxl-ui): add cxl-dashboard-notification component

- packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-accordion-panel.scss
- packages/cxl-ui/scss/global/cxl-vaadin-accordion.scss
- packages/storybook/cxl-ui/cxl-light-card/light-card-slider.stories.js
- packages/storybook/cxl-ui/cxl-vaadin-accordion.stories.js
- packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-dashboard-category.data.json
- packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-dashboard-category.story.js
https://app.clickup.com/t/861n0qkvd
Dependencies:
- #289
> feat: add dashboard category accordion

- packages/cxl-lumo-styles/scss/themes/vaadin-details.scss
- packages/cxl-ui/scss/cxl-dashboard-header.scss
- packages/cxl-ui/scss/cxl-stats.scss
- packages/cxl-ui/scss/global/cxl-dashboard-header.scss
- packages/cxl-ui/scss/global/cxl-stats.scss
- packages/cxl-ui/src/components/cxl-dashboard-header.js
- packages/storybook/cxl-ui/cxl-dashboard-header/template.stories.js
- packages/storybook/cxl-ui/cxl-stats/default.stories.js
- packages/storybook/cxl-ui/cxl-stats/theme=cxl-dashboard-header.data.json
https://app.clickup.com/t/861n0qhy4
> feat(cxl-ui): add `cxl-dashboard-header` component

- packages/cxl-lumo-styles/scss/themes/vaadin-overlay.scss
- packages/cxl-ui/scss/global/cxl-course-dialog.scss
- packages/cxl-ui/src/components/cxl-course-dialog.js
- packages/storybook/cxl-ui/cxl-course-dialog/default.stories.js
https://app.clickup.com/t/861n0qm4w
> feat(cxl-ui): add `cxl-course-dialog` component

- packages/cxl-lumo-styles/scss/themes/vaadin-accordion-panel.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-details.scss
- packages/cxl-ui/scss/cxl-app-layout/_layout.scss
- packages/cxl-ui/scss/cxl-dashboard-header.scss
- packages/cxl-ui/scss/cxl-dashboard-notification.scss
- packages/cxl-ui/scss/cxl-featured-course-card.scss
- packages/cxl-ui/scss/cxl-stats.scss
- packages/cxl-ui/scss/global/cxl-dashboard-header.scss
- packages/cxl-ui/scss/global/cxl-vaadin-accordion.scss
- packages/cxl-ui/src/components/cxl-dashboard-header.js
- packages/storybook/cxl-ui/cxl-dashboard-layout.stories.js
https://app.clickup.com/t/861n0qhnn
> feat(cxl-ui): add `cxl-dashboard-layout` story 

- packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
- packages/cxl-ui/scss/cxl-dashboard-header.scss
Solved style issues that came up with this [PR](https://github.com/conversionxl/cxl-wpstarter/pull/202).
> fix: fix dashboard header button width and course slider hidden badge

- packages/cxl-lumo-styles/scss/themes/vaadin-tabs.scss
- packages/cxl-ui/scss/cxl-featured-course-card.scss
https://app.clickup.com/t/86ay6yqz4
> fix(cxl-lumo-styles): make featured course slider not clickable

- packages/cxl-ui/scss/cxl-featured-course-card.scss
https://app.clickup.com/t/86ay7bpcp
> fix(cxl-ui): change featured course cta to inline-block

- packages/cxl-ui/scss/cxl-featured-course-card.scss
- packages/storybook/cxl-ui/cxl-featured-course-card/default.stories.js
https://app.clickup.com/t/86ay7c8eh
> fix(cxl-ui): limit featured course description text length

- packages/cxl-ui/src/components/cxl-dashboard-header.js
https://app.clickup.com/t/86ay7qrgf
> fix(cxl-ui): change greeting in cxl-dashboard-header

- packages/cxl-lumo-styles/scss/themes/vaadin-tabs.scss
- packages/cxl-ui/src/components/cxl-tabs-slider.js
- packages/storybook/cxl-ui/cxl-dashboard-layout.stories.js
- packages/storybook/cxl-ui/cxl-featured-course-card/dashboard-slider.stories.js
Task: https://app.clickup.com/t/86ay6gf1q (changing width breaks featured card display)
> fix(cxl-ui): prevent scroller from stopping in between cards

- packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-accordion-panel.scss
- packages/cxl-ui/scss/global/cxl-vaadin-accordion.scss
- packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-dashboard-category.data.json
- packages/storybook/cxl-ui/cxl-vaadin-accordion/theme=cxl-dashboard-category.story.js
https://app.clickup.com/t/86ay6gc3z
> fix(cxl-ui): add dashboard accordion new styles

- packages/cxl-lumo-styles/scss/themes/vaadin-tabs.scss
- packages/cxl-ui/scss/cxl-featured-course-card.scss
https://app.clickup.com/t/86ay7qc6x
Fixes bug found while testing cards responsiveness.
> fix(cxl-ui): fix featured-course-card content clipping

- packages/cxl-ui/scss/cxl-base-card.scss
- packages/cxl-ui/scss/cxl-course-card.scss
- packages/cxl-ui/scss/cxl-light-card.scss
- packages/cxl-ui/scss/cxl-time.scss
- packages/cxl-ui/src/components/cxl-base-card.js
- packages/cxl-ui/src/components/cxl-light-card.js
- packages/storybook/cxl-ui/cxl-course-card/[theme=course|lesson].stories.js
- packages/storybook/cxl-ui/cxl-course-card/course-dashboard-varying-heights.stories.js
- packages/storybook/cxl-ui/cxl-course-card/course-dashboard.stories.js
- packages/storybook/cxl-ui/cxl-course-card/template.js
https://app.clickup.com/t/86aya2zga
> feat(cxl-ui): add missing card themes and related fixes

- packages/cxl-ui/scss/cxl-dashboard-header.scss
- packages/cxl-ui/src/components/cxl-dashboard-header.js
https://app.clickup.com/t/86ayahxza
> fix(cxl-ui): fix dashboard header title mobile spacing

- packages/cxl-lumo-styles/scss/themes/vaadin-tabs.scss
- packages/cxl-ui/src/components/cxl-base-card.js
- packages/cxl-ui/src/components/cxl-course-card.js
- packages/cxl-ui/src/components/cxl-featured-course-card.js
- packages/storybook/cxl-ui/cxl-featured-course-card/default.stories.js
https://app.clickup.com/t/86ayavjb2
> fix(cxl-ui): prevent scroll after card click

- packages/cxl-ui/scss/cxl-base-card.scss
https://app.clickup.com/t/86ay8b72b
> fix(cxl-ui): contain wide imagens withing card avatar shape

- packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
- packages/cxl-ui/src/components/cxl-tabs-slider.js
https://app.clickup.com/t/86ayaubcg
> feat(cxl-ui): add snap scrolling in category-accordion

- packages/cxl-lumo-styles/scss/themes/vaadin-overlay.scss
https://app.clickup.com/t/86aycmmmx
> fix(cxl-ui): fix short height viewport bug

- packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
- packages/storybook/cxl-ui/cxl-light-card/default.stories.js
- packages/storybook/cxl-ui/cxl-light-card/light-card-slider.stories.js
- packages/storybook/cxl-ui/cxl-light-card/template.js
https://app.clickup.com/t/86aycyjwy
> fix(cxl-ui): fix dashboard light card widths

- packages/cxl-ui/scss/cxl-light-card.scss
- packages/cxl-ui/src/components/cxl-dashboard-header.js
* added a comma before the name in the dashboard header
* light-card attributes indent fix
https://app.clickup.com/t/86ayff6df
> fix(cxl-ui): dashboard feedback tweaks

- packages/cxl-ui/scss/cxl-base-card.scss
https://app.clickup.com/t/86ayjuqbj
> fix(cxl-ui): fix poor visibility of main category tag in cards

- packages/cxl-lumo-styles/scss/badge.scss
- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-ui/scss/cxl-base-card.scss
- packages/cxl-ui/scss/cxl-light-card.scss
- packages/cxl-ui/src/components/cxl-base-card.js
- packages/cxl-ui/src/components/cxl-light-card.js
- packages/storybook/cxl-ui/cxl-light-card/default.stories.js
- packages/storybook/cxl-ui/cxl-light-card/template.js
https://app.clickup.com/t/86ayhhg16
> feat(cxl-ui): light-card layout updates

- packages/cxl-ui/scss/global/cxl-checkout-details.scss
- packages/storybook/cxl-ui/cxl-checkout-details.stories.js
https://app.clickup.com/t/86aymxtm1
> fix(cxl-ui): add white space between checkout payment methods

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
- packages/cxl-ui/scss/cxl-app-layout/_layout.scss
- packages/cxl-ui/scss/cxl-certificate-header.scss
- packages/cxl-ui/scss/cxl-featured-course-card.scss
- packages/cxl-ui/scss/cxl-section.scss
- packages/cxl-ui/scss/global/cxl-certificate-header.scss
- packages/cxl-ui/scss/global/cxl-stats.scss
- packages/cxl-ui/src/components/cxl-certificate-header.js
- packages/cxl-ui/src/components/cxl-credential.js
- packages/cxl-ui/src/index-core.js
- packages/storybook/cxl-ui/cxl-certificate-header/certificate-header.stories.js
- packages/storybook/cxl-ui/cxl-certificate-header/template.js
- packages/storybook/cxl-ui/cxl-credential/default.stories.js
- packages/storybook/cxl-ui/cxl-stats/default.stories.js
https://app.clickup.com/t/86ayn4zg9
The credential is not responsive, and I didn't immediately understand how to make it responsive. For some reason, complex responsive logic has been implemented there.
Edit: Replaced it with image
> feat(cxl-ui): minidegree header

- packages/cxl-lumo-styles/scss/themes/cxl-tabs-slider.scss
- packages/cxl-ui/scss/cxl-certificate-header.scss
- packages/cxl-ui/src/components/cxl-tabs-slider.js
https://app.clickup.com/t/86ayn4zg9?comment=90140012671170
> fix(cxl-ui): changed certificate-header title font

- packages/cxl-lumo-styles/scss/themes/cxl-checkout-details.scss
Part of https://github.com/conversionxl/cxl-wpstarter/pull/304
> refactor(cxl-lumo-styles): cxl-checkout-details change section icon to arrow

- packages/cxl-ui/scss/cxl-certificate-header.scss
- packages/cxl-ui/src/components/cxl-certificate-header.js
- packages/cxl-ui/src/components/cxl-credential.js
> Certificate header: credential fit

- packages/cxl-lumo-styles/scss/themes/vaadin-button.scss
- packages/storybook/cxl-lumo-styles/elements.stories.js
https://app.clickup.com/t/86ayg4prn?comment=90140015867452
> feat(cxl-lumo-styles): vaadin-button[theme="linkedin"]

- packages/cxl-ui/src/components/cxl-marketing-nav.js
https://app.clickup.com/t/86azbhf2a
> feat(cxl-ui): [cxl-marketing-nav] disable search on mobile

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-lumo-styles/scss/loading.css
- packages/storybook/cxl-lumo-styles/elements.stories.js
https://app.clickup.com/t/86azbhexr
> feat(cxl-lumo-styles): add button pending state

- packages/cxl-ui/scss/cxl-dashboard-header.scss
- packages/cxl-ui/src/components/cxl-dashboard-header.js
- packages/storybook/cxl-ui/cxl-dashboard-header/dashboard-header.stories.js
- packages/storybook/cxl-ui/cxl-dashboard-header/template.js
https://app.clickup.com/t/86azefd4b
> feat(cxl-ui): cxl-dashboard-header add subscription status

- packages/cxl-ui/scss/global/cxl-app-layout.scss
https://app.clickup.com/t/86azp8r7v
> feat: fix action bar buttons on mobile

- packages/cxl-ui/scss/global/cxl-app-layout.scss
https://github.com/conversionxl/sensei/pull/17#discussion_r1544292463
> refactor(cxl-ui): use pure media for device class names

- packages/cxl-lumo-styles/scss/global.scss
https://app.clickup.com/t/86b040y1c
> feat(cxl-lumo-styles): add spinner to checkout submit button

- packages/cxl-ui/src/index-core.js
https://app.clickup.com/t/86azy6kx9
> feat(cxl-ui): index-core include cxl-stars-rating

- packages/cxl-ui/scss/cxl-course-card.scss
https://cxlworld.slack.com/archives/C01HNLQNVA9/p1715760558848559
> feat(cxl-ui): cxl-course-card update name styles

- packages/cxl-ui/scss/cxl-certificate-header.scss
https://app.clickup.com/t/86b0kry6y
> feat(cxl-lumo-styles): style all links

- packages/cxl-ui/scss/cxl-app-layout/_layout.scss
https://app.clickup.com/t/86b0kt8k5
Screenshot:
> fix(cxl-ui): cxl-app-layout increase action bar z-index

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-lumo-styles/scss/typography.scss
- packages/cxl-ui/scss/global/cxl-stats.scss
https://cxlworld.slack.com/archives/C01HLCTR6NB/p1722958521859759
> refactor(cxl-lumo-styles): typography changes

- packages/cxl-lumo-styles/scss/typography.scss
https://app.clickup.com/t/86b1hfjkv
> fix(cxl-lumo-styles): improve header text wrapping

- packages/storybook/cxl-lumo-styles/elements.stories.js
https://app.clickup.com/t/86b2gwtnn
> fix(storybook): remove unresolved attribute from buttons story

- packages/cxl-ui/scss/cxl-base-card.scss
- packages/cxl-ui/scss/cxl-course-card.scss
- packages/cxl-ui/src/components/cxl-base-card.js
https://app.clickup.com/t/86b3107wu
> fix(cxl-ui): cxl-course-card reduce new and locked element size

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-dialog-overlay.scss
- packages/cxl-ui/src/components/cxl-marketing-nav.js
https://cxlworld.slack.com/archives/C01JABH8AHX/p1741253955326379
> feat: reenable search on mobile and fix styling

- packages/cxl-lumo-styles/scss/block-editor/button.scss
- packages/cxl-lumo-styles/scss/wp-block-editor.scss
https://app.clickup.com/t/86b2gwt6f
Depends: https://github.com/conversionxl/cxl-wpstarter/pull/436
> feat(cxl-lumo-styles): block editor add basic button styles

- packages/cxl-lumo-styles/scss/global.scss
- packages/cxl-lumo-styles/scss/themes/vaadin-button.scss
- packages/cxl-ui/scss/cxl-app-layout/_layout.scss
- packages/cxl-ui/scss/cxl-marketing-nav.scss
- packages/cxl-ui/scss/cxl-section.scss
- packages/cxl-ui/src/components/cxl-app-layout.js
- packages/storybook/cxl-ui-neo-brutal/cxl-app-layout/layout=1c-c.stories.js
- packages/storybook/cxl-ui-neo-brutal/cxl-app-layout/layout=1c-w.stories.js
- packages/storybook/cxl-ui-neo-brutal/cxl-app-layout/layout=1c.stories.js
- packages/storybook/cxl-ui-neo-brutal/cxl-app-layout/layout=2c-l.stories.js
- packages/storybook/cxl-ui-neo-brutal/cxl-app-layout/layout=2c-r-short-content.stories.js
- packages/storybook/cxl-ui-neo-brutal/cxl-app-layout/layout=2c-r.stories.js
https://app.clickup.com/t/86b583azf
> b2b phase 2
